some more improvements

diff --git a/trunk/jeriko/load-environment b/trunk/jeriko/load-environment
--- a/trunk/jeriko/load-environment
+++ b/trunk/jeriko/load-environment
@@ -1,21 +1,52 @@
-#!/bin/sh
+#!/bin/bash
+
+#
+# FIND PGREP
+# 
+if [ ! -x `which pgrep` ]
+then
+	echo '[x] cannot find pgrep' 1>&2
+	exit
+fi
+
+#
+# FIND PKILL
+# 
+if [ ! -x `which pgrep` ]
+then
+	echo '[x] cannot find pkill' 1>&2
+	exit
+fi
+
+#
+# KILL ALL
+# kill all child processes when CTRL+C
+#
+KILL_ALL() { pkill -P $$; exit; }
+
+trap KILL_ALL INT
+
 #
 # PATH
+# set PATH to point to jeriko's folder first
 #
 export PATH=`dirname $0`:$PATH
 
 #
 # RUN IN PARALLEL
+# environment variables specific to run-in-parallel and flx-in-parallel
 #
 RUN_IN_PARALLEL_MAX_PROCESSES=10
+RUN_IN_PARALLEL_MAX_WAIT=10
 
 #
 # NMAP
+# configure nmap
 #
 if [ ! -x `which nmap` ]
 then
 	echo '[x] cannot find nmap' 1>&2
-	exit 1
+	exit
 fi
 
 NMAP_TCP_SCAN_METHOD="-sS -P0"
@@ -23,11 +54,12 @@ NMAP_UDP_SCAN_METHOD="-sU -P0"
 
 #
 # NESSUS
+# configure nessus
 #
 if [ ! -x `which nessus` ]
 then
 	echo '[x] cannot find nessus' 1>&2
-	exit 1
+	exit
 fi
 
 NESSUS_HOST=127.0.0.1
@@ -37,6 +69,7 @@ NESSUS_PASS=pass
 
 #
 # LOAD USER DEFINED
+# load jeriko profile from the user's folder
 #
 if [ -f ~/.jerikorc ]
 then
@@ -45,8 +78,28 @@ fi
 
 #
 # LOAD SESSION SPECIFIC
+# load jeriko profile from the current folder
 #
 if [ -f ./.jerikorc ]
 then
 	. ./.jerikorc
+fi
+
+#
+# JERIKO STRICT CHECKS
+#
+if [ "$JERIKO_STRICT_CHECKS" ]
+then
+	#
+	# NESSUSD
+	# detect if nessusd is running
+	#
+	if [ "$NESSUS_HOST" = "127.0.0.1" -o "$NESSUS_HOST" = "localhost" ]
+	then
+		if [ ! `pgrep '^nessusd$'` ]
+		then
+			echo '[x] cannot find nessusd' 1>&2
+			exit
+		fi
+	fi
 fi
